name: ChatEmojis
main: xyz.oribuin.chatemojis.ChatEmojis
version: '1.3.0'
author: Oribuin
api-version: "1.13"
description: Create your own customizable emojis to spice up your chat!
website: https://oribuin.xyz/
softdepend:
  - PlaceholderAPI
  - Vault