name: ChatEmojis
main: xyz.oribuin.chatemojis.ChatEmojis
version: '@version@'
author: Oribuin
api-version: "1.13"
description: Create your own customizable emojis to spice up your chat!
website: https://oribuin.xyz/
softdepend:
  - PlaceholderAPI
  - Vault

commands:
  chatemoji:
    description: Main plugin command.
    usage: /chatemoji
    aliases:
      - chatemojis
      - emojis

permissions:
  chatemojis.*:
    default: op
    description: All permissions for the plugin.
    children:
      - chatemojis.menu
      - chatemojis.menu.other
      - chatemojis.reload
      - chatemojis.create

  chatemojis.menu:
    description: Open the /emojis menu.
    default: op

  chatemojis.menu.other:
    description: Open the /emojis menu for another player.
    default: op
    children:
      - chatemojis.menu

  chatemojis.reload:
    description: Reload the plugin's configuration files.
    default: op

  chatemojis.create:
    description: Create an emoji.
    default: op